version: "3.4"
services:
  neko:
    build: .m1k1o/chromium
    container_name: neko_chromium
    restart: always
    shm_size: "1gb"
    ports:
      - "80:8080"
      - "59000-59100:59000-59100/udp"
    cap_add:
      - SYS_ADMIN
    environment:
      DISPLAY: :99.0
      NEKO_SCREEN: '1280x720@30'
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_BIND: :8080
      NEKO_EPR: 59000-59100
      NEKO_NAT1TO1: 192.168.1.20
